### ISSUE TITLE
[Feature Request]:  COCO formate read json

### ISSUE THREAD

**Issue by Lifeguard-alex** [visual-layer/fastdup#202] opened 2023-05-17 19:04 UTC
### Feature Name

coco formate

### Feature Description

i dont see option to read coco formate json file for object detector

### Contact Information [Optional]

alex@lifeguard-ai.com

**Comment by amirmk89** [comment] 2023-05-18 06:18
Duplicate of #203

**Comment by Lifeguard-alex** [comment] 2023-05-19 10:38
hi , thnks for the answer 
the code exmaple is missing this :
 defaultdict(int)
class_id
img_id

do you have a full code exmaple for this ?

**Comment by dbickson** [comment] 2023-05-19 14:40
hi @Lifeguard-alex send us your json and we will make an example for you it seems your json does not include img_id and class_id which are supposed to be there.

**Comment by dbickson** [comment] 2023-05-27 18:31
hi @Lifeguard-alex coco annotations are now supported in fastdup, see this Kaggle tutorial notebook: https://www.kaggle.com/code/graphlab/fastdup-coco-format-tutorial

**Closed by dbickson** 2023-05-27 18:31 UTC
