### ISSUE TITLE
[Bug]: fastdup import very slowly

### ISSUE THREAD

**Issue by zhbUp** [visual-layer/fastdup#262] opened 2023-09-01 09:01 UTC
### What happened?

i installed the fastdup normally on ubantu 1804, baseed on python 3.8, when i import fastdup everytime, it takes so long, actually spent 523 seconds

### What did you expect to see?

I really wish it will as silky smooth as other small libraries.

### What version of fastdup were you runnning on?

v1.36

### What version of Python were you running on?

Python 3.8

### Operating System

Ubuntu 1804

**Comment by dbickson** [comment] 2023-09-01 15:49
hello @zhbUp thanks for reporting!
I believe the issue is probably firewall since we are using requests.get to check for newer python version, we will add a 2 second timeout and release version 1.38 today.

**Comment by dbickson** [comment] 2023-09-03 03:39
Should be fixed in 1.38

**Closed by dbickson** 2023-09-03 03:39 UTC
Labels: bug

**Comment by zhbUp** [comment] 2023-09-04 01:07
Thank you very much. According to your prompts, I can quickly import the request after commenting out the request. The source code of version 1.38 installed by pip and the master branch do not see your submission.
